name: nb-do-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/nhuet/workflow_testing@fa1d1bdc1807bcd1a29d57847af748e712bfd195#egg=discrete-optimization
      - nbgitpuller
