name: nb-do-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - discrete-optimization==0.3.14
      - --extra-index-url https://test.pypi.org/simple/
      - nbgitpuller
