name: nb-do-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/nhuet/workflow_testing@39a2073ad7d2b38f20f9694413eb09b0d1e3b246#egg=discrete-optimization
      - nbgitpuller
