name: nb-do-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/nhuet/workflow_testing@68dbcf04fd727dc590013eee20d0195b39e3b141#egg=discrete-optimization
      - nbgitpuller
