name: nb-do-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/nhuet/workflow_testing@e567ac6a1aeeedcf28ef359256c9b6682bc3b7b9#egg=discrete-optimization
      - nbgitpuller
