name: nb-do-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/nhuet/workflow_testing@886104bd28e38fa7dece2c9193c7e016bba031f1#egg=discrete-optimization
      - nbgitpuller
