# This is a basic workflow to help you get started with Actions

name: CI 🔨

# Controls when the workflow will run
on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tests
        run: |
          git checkout binder
          git branch
          ls

          git checkout pull/7/merge
          git branch
          ls

          LOCAL_REF=${GITHUB_REF/refs//}
          git checkout ${LOCAL_REF}
          git branch
          ls

          git checkout ${{ github.head_ref }}
          git branch
          ls





          echo $GITHUB_REF
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.repository }}
          echo $GITHUB_REPOSITORY

          ls
          git branch
          git checkout ${{ github.ref }}
          git branch
          ls

      - name: Set env variables for github+binder links in doc
        run: |
          # binder environment repo and branch
          AUTODOC_BINDER_ENV_GH_REPO_NAME="airbus/scikit-decide"
          AUTODOC_BINDER_ENV_GH_BRANCH="binder"
          # notebooks source repo and branch depending if it is a commit push or a PR
          if [[ $GITHUB_REF == refs/pull* ]];
          then
              AUTODOC_NOTEBOOKS_REPO_URL="${GITHUB_SERVER_URL}/${{ github.event.pull_request.head.repo.full_name }}"
              AUTODOC_NOTEBOOKS_BRANCH=${GITHUB_HEAD_REF}
          elif [[ $GITHUB_REF == refs/heads* ]];
          then
              AUTODOC_NOTEBOOKS_REPO_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
              AUTODOC_NOTEBOOKS_BRANCH=${GITHUB_REF/refs\/heads\//}
          fi
          # export in GITHUB_ENV for next steps
          echo "AUTODOC_BINDER_ENV_GH_REPO_NAME=${AUTODOC_BINDER_ENV_GH_REPO_NAME}" >> $GITHUB_ENV
          echo "AUTODOC_BINDER_ENV_GH_BRANCH=${AUTODOC_BINDER_ENV_GH_BRANCH}" >> $GITHUB_ENV
          echo "AUTODOC_NOTEBOOKS_REPO_URL=${AUTODOC_NOTEBOOKS_REPO_URL}" >> $GITHUB_ENV
          echo "AUTODOC_NOTEBOOKS_BRANCH=${AUTODOC_NOTEBOOKS_BRANCH}" >> $GITHUB_ENV
          # check computed variables
          echo "Binder env: ${AUTODOC_BINDER_ENV_GH_REPO_NAME}/${AUTODOC_BINDER_ENV_GH_BRANCH}"
          echo "Notebooks source: ${AUTODOC_NOTEBOOKS_REPO_URL}/tree/${AUTODOC_NOTEBOOKS_BRANCH}"

      - name: read binder env
        run: |
          echo ${AUTODOC_BINDER_ENV_GH_REPO_NAME}
          echo ${AUTODOC_BINDER_ENV_GH_BRANCH}
          echo ${AUTODOC_NOTEBOOKS_REPO_URL}
          echo ${AUTODOC_NOTEBOOKS_BRANCH}

          echo nb_branch: ${{ env.AUTODOC_NOTEBOOKS_BRANCH }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo  ${{ github.ref }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo deploy
