name: Build discrete-optimization

on:
  push:
    branches:
      - "**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-github-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: test
        run: | 
          echo ${{ github.workflow }}-${{ github.ref }}
          echo $GITHUB_REF
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.repository }}
          echo $GITHUB_REPOSITORY
          echo ${{ github }}
