name: Build workflow-testing

on:
  push:
    branches:
      - "**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-sb3:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python -m pip install gymnasium stable-baselines3 "numpy>=2.0" 
          python ex.py        
