name: Build workflow-testing

on:
  push:
    branches:
      - "**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-gym:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          # preinstall gym==0.21.0 with older pip + --no-use-pep517 because its requirements list is broken
          python -m pip install pip<23.1  # starting with pip 23.1, gym 0.21.0 is not intallable anymore
          python -m pip install wheel
          python -m pip install gym==0.21.0 --no-use-pep517
          # install remaining dependencies
          python -m pip install --upgrade pip
          python -m pip install pytest docopt commonmark
          
