name: Build workflow-testing

on:
  push:
    branches:
      - "**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-gym:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.10" ]
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          # preinstall gym==0.21.0 with legacy method (python setup.py) because its requirements list is broken
          python -m pip install "pip==22"  # starting with pip 23.1, gym 0.21.0 is not intallable anymore
          python -m pip uninstall -y wheel  # wheel must not be here to fall back directly to python setup.py
          python -m pip install gym==0.21.0 --no-use-pep517
          # install remaining dependencies
          python -m pip install --upgrade pip
          python -m pip install pytest docopt commonmark
          
