name: Build workflow-testing

on:
  push:
    branches:
      - "**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-archi:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: ["macos-latest", "macos-12"]
        arch: ["arm64", "x86_64"]
        exclude:
          - os: macos-12
            arch: arm64
          - os: macos-latest
            arch: x86_64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - run: | 
          echo ${{ matrix }}
          uname -a
