name: Build workflow-testing

on:
  push:
    branches:
      - "**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    strategy:
      matrix:
        python-version: [ "3.8", "3.9" ]
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        nodeellip: [ false, true ]
        tf212: [ false, true ]
        exclude:
          - os: "windows-latest"
            nodeellip: true
          - os: "macos-latest"
            nodeellip: true
          - os: "ubuntu-latest"
            nodeellip: true
            python-version: 3.9
          - os: "windows-latest"
            tf212: true
          - os: "macos-latest"
            tf212: true
          - os: "ubuntu-latest"
            tf212: true
            python-version: 3.9
          - os: "ubuntu-latest"
            tf212: true
            nodeellip: false
            python-version: 3.8

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Chekc strategy
        run: |
          echo ${{ matrix.python-version }}
          echo ${{ matrix.os }}
          echo ${{ matrix.nodeellip }}
          echo ${{ matrix.tf212 }}