name: Build workflow-testing

on:
  push:
    branches:
      - "**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test_bash:
    runs-on: ubuntu-latest
    steps:
      - name: Script
        run: |
          echo ok
          return_code=0 
          bash -c 'exit 0'|| ret_code=$?
          if [ $ret_code != 0 ]; then return_code=$ret_code; fi
          echo $return_code
          bash -c 'exit 12' || ret_code=$?
          if [ $ret_code != 0 ]; then return_code=$ret_code; fi
          echo $return_code
          bash -c 'exit 0'|| ret_code=$?
          if [ $ret_code != 0 ]; then return_code=$ret_code; fi
          echo $return_code
          bash -c 'exit 12' || ret_code=$?
          if [ $ret_code != 0 ]; then return_code=$ret_code; fi
          echo $return_code
          
