name: Build workflow-testing

on:
  push:
    branches:
      - "**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "windows-latest", "ubuntu-latest"]
        python-version: ["3.10", "3.13"]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout discrete-optimization source code
        uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: install deps
        run: pip install "pytest<9.1.0"
      - name: Test all tests
        run: pytest --co  tests
      - name: Test normal tests
        run: pytest --co --ignore-glob=tests/**/test_*non_regression.py tests
      - name: Test non-regression tests
        run: |
          non_regression_test_files=$(python tests/find_non_regression_tests.py)
          echo $non_regression_test_files
          ls tests/**/test_*non_regression.py
          shopt -s globstar  # enable **
          ls tests/**/test_*non_regression.py
          pwd
          ls $non_regression_test_files
          
          pytest --co $non_regression_test_files

